//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appClient.InfoManageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminHeader", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class AdminHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventAddViewModel", Namespace="http://schemas.datacontract.org/2004/07/rsiProj1.ViewModels")]
    [System.SerializableAttribute()]
    public partial class EventAddViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventEditViewModel", Namespace="http://schemas.datacontract.org/2004/07/rsiProj1.ViewModels")]
    [System.SerializableAttribute()]
    public partial class EventEditViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InfoManageService.IInfoManageService")]
    public interface IInfoManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoManageService/AddEvent", ReplyAction="http://tempuri.org/IInfoManageService/AddEventResponse")]
        appClient.InfoManageService.MessageBoxOf_Guid AddEvent(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventAddViewModel request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoManageService/AddEvent", ReplyAction="http://tempuri.org/IInfoManageService/AddEventResponse")]
        System.Threading.Tasks.Task<appClient.InfoManageService.MessageBoxOf_Guid> AddEventAsync(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventAddViewModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoManageService/EditEvent", ReplyAction="http://tempuri.org/IInfoManageService/EditEventResponse")]
        appClient.InfoManageService.MessageBoxOf_Guid EditEvent(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventEditViewModel request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoManageService/EditEvent", ReplyAction="http://tempuri.org/IInfoManageService/EditEventResponse")]
        System.Threading.Tasks.Task<appClient.InfoManageService.MessageBoxOf_Guid> EditEventAsync(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventEditViewModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoManageService/RemoveEvent", ReplyAction="http://tempuri.org/IInfoManageService/RemoveEventResponse")]
        appClient.InfoManageService.MessageBoxOf_Boolean RemoveEvent(appClient.InfoManageService.MessageBoxOf_AdminHeader_Guid request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfoManageService/RemoveEvent", ReplyAction="http://tempuri.org/IInfoManageService/RemoveEventResponse")]
        System.Threading.Tasks.Task<appClient.InfoManageService.MessageBoxOf_Boolean> RemoveEventAsync(appClient.InfoManageService.MessageBoxOf_AdminHeader_Guid request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageBoxOf_AdminHeader_EventAddViewModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageBoxOf_AdminHeader_EventAddViewModel {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public appClient.InfoManageService.AdminHeader Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public appClient.InfoManageService.EventAddViewModel Body;
        
        public MessageBoxOf_AdminHeader_EventAddViewModel() {
        }
        
        public MessageBoxOf_AdminHeader_EventAddViewModel(appClient.InfoManageService.AdminHeader Header, appClient.InfoManageService.EventAddViewModel Body) {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageBoxOf_Guid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageBoxOf_Guid {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid Body;
        
        public MessageBoxOf_Guid() {
        }
        
        public MessageBoxOf_Guid(System.Guid Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageBoxOf_AdminHeader_EventEditViewModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageBoxOf_AdminHeader_EventEditViewModel {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public appClient.InfoManageService.AdminHeader Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public appClient.InfoManageService.EventEditViewModel Body;
        
        public MessageBoxOf_AdminHeader_EventEditViewModel() {
        }
        
        public MessageBoxOf_AdminHeader_EventEditViewModel(appClient.InfoManageService.AdminHeader Header, appClient.InfoManageService.EventEditViewModel Body) {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageBoxOf_AdminHeader_Guid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageBoxOf_AdminHeader_Guid {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public appClient.InfoManageService.AdminHeader Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid Body;
        
        public MessageBoxOf_AdminHeader_Guid() {
        }
        
        public MessageBoxOf_AdminHeader_Guid(appClient.InfoManageService.AdminHeader Header, System.Guid Body) {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageBoxOf_Boolean", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MessageBoxOf_Boolean {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Body;
        
        public MessageBoxOf_Boolean() {
        }
        
        public MessageBoxOf_Boolean(bool Body) {
            this.Body = Body;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInfoManageServiceChannel : appClient.InfoManageService.IInfoManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoManageServiceClient : System.ServiceModel.ClientBase<appClient.InfoManageService.IInfoManageService>, appClient.InfoManageService.IInfoManageService {
        
        public InfoManageServiceClient() {
        }
        
        public InfoManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        appClient.InfoManageService.MessageBoxOf_Guid appClient.InfoManageService.IInfoManageService.AddEvent(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventAddViewModel request) {
            return base.Channel.AddEvent(request);
        }
        
        public System.Guid AddEvent(appClient.InfoManageService.AdminHeader Header, appClient.InfoManageService.EventAddViewModel Body) {
            appClient.InfoManageService.MessageBoxOf_AdminHeader_EventAddViewModel inValue = new appClient.InfoManageService.MessageBoxOf_AdminHeader_EventAddViewModel();
            inValue.Header = Header;
            inValue.Body = Body;
            appClient.InfoManageService.MessageBoxOf_Guid retVal = ((appClient.InfoManageService.IInfoManageService)(this)).AddEvent(inValue);
            return retVal.Body;
        }
        
        public System.Threading.Tasks.Task<appClient.InfoManageService.MessageBoxOf_Guid> AddEventAsync(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventAddViewModel request) {
            return base.Channel.AddEventAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        appClient.InfoManageService.MessageBoxOf_Guid appClient.InfoManageService.IInfoManageService.EditEvent(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventEditViewModel request) {
            return base.Channel.EditEvent(request);
        }
        
        public System.Guid EditEvent(appClient.InfoManageService.AdminHeader Header, appClient.InfoManageService.EventEditViewModel Body) {
            appClient.InfoManageService.MessageBoxOf_AdminHeader_EventEditViewModel inValue = new appClient.InfoManageService.MessageBoxOf_AdminHeader_EventEditViewModel();
            inValue.Header = Header;
            inValue.Body = Body;
            appClient.InfoManageService.MessageBoxOf_Guid retVal = ((appClient.InfoManageService.IInfoManageService)(this)).EditEvent(inValue);
            return retVal.Body;
        }
        
        public System.Threading.Tasks.Task<appClient.InfoManageService.MessageBoxOf_Guid> EditEventAsync(appClient.InfoManageService.MessageBoxOf_AdminHeader_EventEditViewModel request) {
            return base.Channel.EditEventAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        appClient.InfoManageService.MessageBoxOf_Boolean appClient.InfoManageService.IInfoManageService.RemoveEvent(appClient.InfoManageService.MessageBoxOf_AdminHeader_Guid request) {
            return base.Channel.RemoveEvent(request);
        }
        
        public bool RemoveEvent(appClient.InfoManageService.AdminHeader Header, System.Guid Body) {
            appClient.InfoManageService.MessageBoxOf_AdminHeader_Guid inValue = new appClient.InfoManageService.MessageBoxOf_AdminHeader_Guid();
            inValue.Header = Header;
            inValue.Body = Body;
            appClient.InfoManageService.MessageBoxOf_Boolean retVal = ((appClient.InfoManageService.IInfoManageService)(this)).RemoveEvent(inValue);
            return retVal.Body;
        }
        
        public System.Threading.Tasks.Task<appClient.InfoManageService.MessageBoxOf_Boolean> RemoveEventAsync(appClient.InfoManageService.MessageBoxOf_AdminHeader_Guid request) {
            return base.Channel.RemoveEventAsync(request);
        }
    }
}
